//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class back_modelo
    {
        public int modeloId { get; set; }
        public string nombre { get; set; }
        public string descripcionBreve { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> precioEstandar { get; set; }
        public string portada { get; set; }
        public Nullable<int> orden { get; set; }
        public Nullable<int> tipo { get; set; }
        public Nullable<int> estado { get; set; }
        public string telefono { get; set; }
        public Nullable<int> distritoId { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
    }
}
