//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Caracteristicas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Caracteristicas()
        {
            this.tbl_Anuncio_Lugar = new HashSet<tbl_Anuncio_Lugar>();
            this.tbl_Anuncio_Servicio = new HashSet<tbl_Anuncio_Servicio>();
        }
    
        public int id_caracteristica { get; set; }
        public Nullable<int> grupo_caracteristica { get; set; }
        public string codigo_caracteristica { get; set; }
        public string descripcion_caracteristica { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Anuncio_Lugar> tbl_Anuncio_Lugar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Anuncio_Servicio> tbl_Anuncio_Servicio { get; set; }
        public virtual tbl_Grupo_Detalle tbl_Grupo_Detalle { get; set; }
    }
}
