//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Distritos
    {
        public int id_distrito { get; set; }
        public Nullable<int> id_departamento { get; set; }
        public Nullable<int> id_provincia { get; set; }
        public string nombre_distrito { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
    
        public virtual tbl_Departamentos tbl_Departamentos { get; set; }
        public virtual tbl_Provincia tbl_Provincia { get; set; }
    }
}
