//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Caracteristicas_Model
    {
        public int id_CaracteristicaAnuncio { get; set; }
        public Nullable<int> id_Anuncio { get; set; }
        public Nullable<int> id_GrupoCaracteristica { get; set; }
        public string id_Nacionalidad { get; set; }
        public string id_Piel { get; set; }
        public string id_CabelloNegro { get; set; }
        public string id_CabelloRubio { get; set; }
        public string id_CabelloCastanio { get; set; }
        public string id_CabelloRojo { get; set; }
        public string id_Estatura { get; set; }
        public string id_Cuerpo { get; set; }
        public string id_Pechos { get; set; }
        public string id_Pubis { get; set; }
        public string atencion_Mujer { get; set; }
        public string atencion_Parejas { get; set; }
        public string atencion_Discapacitados { get; set; }
        public string atencion_Hombres { get; set; }
        public string medioPago_Efectivo { get; set; }
        public string medioPago_Tarjeta { get; set; }
        public string servicio1_1 { get; set; }
        public string servicio1_2 { get; set; }
        public string servicio1_3 { get; set; }
        public string servicio1_4 { get; set; }
        public string servicio1_5 { get; set; }
        public string servicio1_6 { get; set; }
        public string servicio1_7 { get; set; }
        public string servicio1_8 { get; set; }
        public string servicio1_9 { get; set; }
        public string servicio1_10 { get; set; }
        public string servicio1_Otro { get; set; }
        public string servicio2_1 { get; set; }
        public string servicio2_2 { get; set; }
        public string servicio2_3 { get; set; }
        public string servicio2_4 { get; set; }
        public string servicio2_5 { get; set; }
        public string servicio2_6 { get; set; }
        public string servicio2_7 { get; set; }
        public string servicio2_8 { get; set; }
        public string servicio2_Otro { get; set; }
        public string lugarEncuentro_1 { get; set; }
        public string lugarEncuentro_2 { get; set; }
        public string lugarEncuentro_3 { get; set; }
        public string lugarEncuentro_4 { get; set; }
        public string lugarEncuentro_5 { get; set; }
        public string lugarEncuentro_6 { get; set; }
        public string lugarEncuentro_Otro { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
    }
}
