//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Anuncio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Anuncio()
        {
            this.tbl_Anuncio_Servicio = new HashSet<tbl_Anuncio_Servicio>();
            this.tbl_Anuncio_Horarios = new HashSet<tbl_Anuncio_Horarios>();
            this.tbl_Anuncio_Lugar = new HashSet<tbl_Anuncio_Lugar>();
            this.tbl_Anuncio_Caracteristicas = new HashSet<tbl_Anuncio_Caracteristicas>();
            this.tbl_Anuncio_Tarifa = new HashSet<tbl_Anuncio_Tarifa>();
        }
    
        public int id_Anuncio { get; set; }
        public Nullable<int> id_Usuario { get; set; }
        public string email_usuario { get; set; }
        public Nullable<int> id_Categoria { get; set; }
        public string CodigoPostal_Usuario { get; set; }
        public string telefono_Anuncion { get; set; }
        public Nullable<int> id_Departemento { get; set; }
        public Nullable<int> id_Distrito { get; set; }
        public string titulo_anuncio { get; set; }
        public string descripcion_anuncio { get; set; }
        public string nombre_anuncio { get; set; }
        public Nullable<int> edad_anuncio { get; set; }
        public string audio_anuncio { get; set; }
        public Nullable<int> contactoWhatsapp { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public string portada { get; set; }
        public Nullable<int> tipo_Anuncio { get; set; }
        public string latitud_anuncio { get; set; }
        public string longitud_anuncio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Anuncio_Servicio> tbl_Anuncio_Servicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Anuncio_Horarios> tbl_Anuncio_Horarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Anuncio_Lugar> tbl_Anuncio_Lugar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Anuncio_Caracteristicas> tbl_Anuncio_Caracteristicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Anuncio_Tarifa> tbl_Anuncio_Tarifa { get; set; }
    }
}
