//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Usuarios
    {
        public int id_usuario { get; set; }
        public string CodigoPostal_Usuario { get; set; }
        public string nroCelular_Usuario { get; set; }
        public string email_usuario { get; set; }
        public string contrasena_usuario { get; set; }
        public string nombre_usuario { get; set; }
        public Nullable<int> idPreferencias { get; set; }
        public Nullable<int> vip_usuario { get; set; }
        public string nro_tarjeta { get; set; }
        public string cvv_tarjeta { get; set; }
        public Nullable<System.DateTime> fechaVec_tarjeta { get; set; }
        public Nullable<int> subscripcion_usuario { get; set; }
        public string nombre_tarjeta { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public string codigo_verification { get; set; }
    }
}
