//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Provincia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Provincia()
        {
            this.tbl_Distritos = new HashSet<tbl_Distritos>();
        }
    
        public int id_provincia { get; set; }
        public Nullable<int> id_departamento { get; set; }
        public string nombre_provincia { get; set; }
        public string estado { get; set; }
        public string usuario_creacion { get; set; }
        public string fecha_creacion { get; set; }
    
        public virtual tbl_Departamentos tbl_Departamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Distritos> tbl_Distritos { get; set; }
    }
}
