//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Anuncio_Caracteristicas
    {
        public int id_CaracteristicaAnuncio { get; set; }
        public Nullable<int> id_Anuncio { get; set; }
        public Nullable<int> id_Nacionalidad { get; set; }
        public Nullable<int> id_Piel { get; set; }
        public Nullable<int> id_Cabello { get; set; }
        public Nullable<int> id_Estatura { get; set; }
        public Nullable<int> id_Cuerpo { get; set; }
        public Nullable<int> id_Pechos { get; set; }
        public Nullable<int> id_Pubis { get; set; }
        public string atencion_Mujer { get; set; }
        public string atencion_Parejas { get; set; }
        public string atencion_Discapacitados { get; set; }
        public string atencion_Hombres { get; set; }
        public string medioPago_Efectivo { get; set; }
        public string medioPago_Tarjeta { get; set; }
        public string otro_Servicio { get; set; }
        public string otro_ServicioEspecial { get; set; }
        public string otro_Lugar { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
    
        public virtual tbl_Anuncio tbl_Anuncio { get; set; }
    }
}
